"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./auth.routes"));
const users_route_1 = __importDefault(require("../api/users/users.route"));
const course_routes_1 = __importDefault(require("../api/course/course.routes"));
const news_route_1 = __importDefault(require("../api/news/news.route"));
const alumni_route_1 = __importDefault(require("../api/alumni/alumni.route"));
const recognitions_route_1 = __importDefault(require("./../api/recognitions/recognitions.route"));
const team_route_1 = __importDefault(require("../api/teams/team.route"));
const holidat_route_1 = __importDefault(require("../api/holiday/holidat.route"));
const downloads_route_1 = __importDefault(require("../api/downloads/downloads.route"));
const notice_route_1 = __importDefault(require("../api/notice/notice.route"));
const intake_route_1 = __importDefault(require("../api/intake-calender/intake.route"));
const planner_routes_1 = require("../api/academic-planner/planner.routes");
const contact_route_1 = __importDefault(require("../api/contact/contact.route"));
const achievement_route_1 = __importDefault(require("../api/achievement/achievement.route"));
const gallery_route_1 = __importDefault(require("../api/media/gallery.route"));
const connect_routes_1 = __importDefault(require("../api/connect/connect.routes"));
const document_route_1 = __importDefault(require("../api/documents/document.route"));
const journal_route_1 = require("../api/journal/journal.route");
const editorial_route_1 = __importDefault(require("../api/editorial-board/editorial.route"));
const planner_course_route_1 = __importDefault(require("../api/planner-course/planner-course.route"));
const alumni_routes_1 = __importDefault(require("../api/alumni-form/alumni-routes"));
const planner_routes_2 = require("../api/fee-planner/planner.routes");
const emal_router_1 = __importDefault(require("../api/emails/emal.router"));
const scholarship_router_1 = __importDefault(require("../api/scholarship/scholarship-router"));
const department_route_1 = __importDefault(require("../api/teams/department.route"));
const course_category_route_1 = __importDefault(require("../api/course/category/course-category.route"));
const rootRouter = (0, express_1.Router)();
rootRouter.use("/auth", auth_routes_1.default);
rootRouter.use("/users", users_route_1.default);
rootRouter.use("/course-categories", course_category_route_1.default);
rootRouter.use("/courses", course_routes_1.default);
rootRouter.use("/news", news_route_1.default);
rootRouter.use("/alumni", alumni_route_1.default);
rootRouter.use("/recognition", recognitions_route_1.default);
rootRouter.use("/teams", team_route_1.default);
rootRouter.use("/dept", department_route_1.default);
rootRouter.use("/holiday", holidat_route_1.default);
rootRouter.use("/downloads", downloads_route_1.default);
rootRouter.use("/notice", notice_route_1.default);
rootRouter.use("/intake", intake_route_1.default);
rootRouter.use("/planner", planner_routes_1.plannerRouter);
rootRouter.use("/gallery", gallery_route_1.default);
rootRouter.use("/connect", connect_routes_1.default);
rootRouter.use("/fee-planner", planner_routes_2.feePlannerRouter);
rootRouter.use("/achivement", achievement_route_1.default);
rootRouter.use("/contact", contact_route_1.default);
rootRouter.use("/docs", document_route_1.default);
rootRouter.use("/alumni-form", alumni_routes_1.default);
rootRouter.use("/join-students", emal_router_1.default);
rootRouter.use("/scholarship", scholarship_router_1.default);
rootRouter.use("/journal", journal_route_1.journalRouter);
rootRouter.use("/planner-course", planner_course_route_1.default);
rootRouter.use("/editorial", editorial_route_1.default);
exports.default = rootRouter;
