export enum EPermission {
  USERS = "USERS",
  COURSES = "COURSES",
  TEAMS = "TEAMS",
  ALUMNI = "ALUMNI",

  NEWS = "NEWS",
  JOURNALS = "JOURNALS",
  EDITORIAL_BOARD = "EDITORIAL_BOARD",
  CONNECT = "CONNECT",
  GALLERY = "GALLERY",

  NOTICE = "NOTICE",
  CONTACT = "CONTACT",
  HOLIDAY = "HOLIDAY",
  RECOGNITION = "RECOGNITION",
  ACHIEVEMENT = "ACHIEVEMENT",

  INTAKE = "INTAKE",
  DOCUMENTS = "DOCUMENTS",

  ACADEMIC_PLANNER = "ACADEMIC_PLANNER",
  FEE_PLANNER = "FEE_PLANNER",
  DOWNLOADS = "DOWNLOADS",
}
